iso: ARE

links:
- level: 0
  boundary_year: 1995
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/ARE/ADM0/geoBoundaries-ARE-ADM0.geojson

- level: 1
  boundary_year: 2017
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/ARE/ADM1/geoBoundaries-ARE-ADM1.geojson

