iso: BDI

links:
- level: 0
  boundary_year: 2006
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BDI/ADM0/geoBoundaries-BDI-ADM0.geojson

- level: 1
  boundary_year: 2014
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BDI/ADM1/geoBoundaries-BDI-ADM1.geojson

- level: 2
  boundary_year: 2007
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BDI/ADM2/geoBoundaries-BDI-ADM2.geojson

- level: 3
  boundary_year: 2015
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BDI/ADM3/geoBoundaries-BDI-ADM3.geojson

