iso: BEL

links:
- level: 0
  boundary_year: 2022
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BEL/ADM0/geoBoundaries-BEL-ADM0.geojson

- level: 1
  boundary_year: 2022
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BEL/ADM1/geoBoundaries-BEL-ADM1.geojson

- level: 2
  boundary_year: 2015
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BEL/ADM2/geoBoundaries-BEL-ADM2.geojson

- level: 3
  boundary_year: 2014
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BEL/ADM3/geoBoundaries-BEL-ADM3.geojson

- level: 4
  boundary_year: 2018
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BEL/ADM4/geoBoundaries-BEL-ADM4.geojson

