iso: BRN

links:
- level: 0
  boundary_year: 2015
  link: https://github.com/wmgeolab/geoBoundaries/raw/f549eab/releaseData/gbOpen/BRN/ADM0/geoBoundaries-BRN-ADM0.geojson

- level: 1
  boundary_year: 2011
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BRN/ADM1/geoBoundaries-BRN-ADM1.geojson

- level: 2
  boundary_year: 2006
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BRN/ADM2/geoBoundaries-BRN-ADM2.geojson

