iso: IRL

links:
- level: 0
  boundary_year: 2017
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/IRL/ADM0/geoBoundaries-IRL-ADM0.geojson

- level: 1
  boundary_year: 2022
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/IRL/ADM1/geoBoundaries-IRL-ADM1.geojson

- level: 2
  boundary_year: 2015
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/IRL/ADM2/geoBoundaries-IRL-ADM2.geojson

- level: 3
  boundary_year: 2017.0
  link: https://github.com/wmgeolab/geoBoundaries/raw/ebae58c97e4774de9b5574dd33e77f4062422bbf/releaseData/gbOpen/IRL/ADM3/geoBoundaries-IRL-ADM3.geojson

