iso: ITA

links:
- level: 0
  boundary_year: 2023
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/ITA/ADM0/geoBoundaries-ITA-ADM0.geojson

- level: 1
  boundary_year: 2023
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/ITA/ADM1/geoBoundaries-ITA-ADM1.geojson

- level: 2
  boundary_year: 2023
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/ITA/ADM2/geoBoundaries-ITA-ADM2.geojson

- level: 3
  boundary_year: 2023
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/ITA/ADM3/geoBoundaries-ITA-ADM3.geojson

- level: 4
  boundary_year: 2023
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/ITA/ADM4/geoBoundaries-ITA-ADM4.geojson

