iso: MRT

links:
- level: 0
  boundary_year: 2020
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/MRT/ADM0/geoBoundaries-MRT-ADM0.geojson

- level: 1
  boundary_year: 2015
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/MRT/ADM1/geoBoundaries-MRT-ADM1.geojson

- level: 2
  boundary_year: 2020
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/MRT/ADM2/geoBoundaries-MRT-ADM2.geojson

