iso: SGP

links:
- level: 0
  boundary_year: 2016
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/SGP/ADM0/geoBoundaries-SGP-ADM0.geojson

- level: 1
  boundary_year: 2016
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/SGP/ADM1/geoBoundaries-SGP-ADM1.geojson

- level: 2
  boundary_year: 2016
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/SGP/ADM2/geoBoundaries-SGP-ADM2.geojson

