iso: SLE

links:
- level: 0
  boundary_year: 2016
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/SLE/ADM0/geoBoundaries-SLE-ADM0.geojson

- level: 1
  boundary_year: 2014
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/SLE/ADM1/geoBoundaries-SLE-ADM1.geojson

- level: 2
  boundary_year: 2017
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/SLE/ADM2/geoBoundaries-SLE-ADM2.geojson

- level: 3
  boundary_year: 2016
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/SLE/ADM3/geoBoundaries-SLE-ADM3.geojson

- level: 4
  boundary_year: 2016
  link: https://github.com/wmgeolab/geoBoundaries/raw/9348641/releaseData/gbOpen/SLE/ADM4/geoBoundaries-SLE-ADM4.geojson

