iso: TKM

links:
- level: 0
  boundary_year: 2007
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/TKM/ADM0/geoBoundaries-TKM-ADM0.geojson

- level: 1
  boundary_year: 2007
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/TKM/ADM1/geoBoundaries-TKM-ADM1.geojson

- level: 2
  boundary_year: 2009
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/TKM/ADM2/geoBoundaries-TKM-ADM2.geojson

