iso: VEN

links:
- level: 0
  boundary_year: 2021
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/VEN/ADM0/geoBoundaries-VEN-ADM0.geojson

- level: 1
  boundary_year: 2020
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/VEN/ADM1/geoBoundaries-VEN-ADM1.geojson

- level: 2
  boundary_year: 2015
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/VEN/ADM2/geoBoundaries-VEN-ADM2.geojson

