iso: VUT

links:
- level: 0
  boundary_year: 2017
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/VUT/ADM0/geoBoundaries-VUT-ADM0.geojson

- level: 1
  boundary_year: 2017
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/VUT/ADM1/geoBoundaries-VUT-ADM1.geojson

- level: 2
  boundary_year: 2019
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/VUT/ADM2/geoBoundaries-VUT-ADM2.geojson

- level: 3
  boundary_year: 2014
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/VUT/ADM3/geoBoundaries-VUT-ADM3.geojson

