defaults:
  - _self_
  - geoboundaries: AGO # possible options are ADM0-ADM5 and all ISO codes

output_dir: outdir/

overwrite: False # whether you want to potentially overwrite previous downloads

dry_run: True # to test functionality without downloading anything
