defaults:
  - _self_
  - geoboundaries: ADM0 # possible options are ADM0-ADM5 and all ISO codes

links: ${geoboundaries} #necessary hack to get snakemake and hydra compatible

output_dir: outdir/ADM0

dry_run: False # to test functionality without downloading anything

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}