iso: BLR

links:
- level: 0
  boundary_year: 2019
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BLR/ADM0/geoBoundaries-BLR-ADM0.geojson

- level: 1
  boundary_year: 2005
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BLR/ADM1/geoBoundaries-BLR-ADM1.geojson

- level: 2
  boundary_year: 2005
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BLR/ADM2/geoBoundaries-BLR-ADM2.geojson

