iso: COD

links:
- level: 0
  boundary_year: 2017
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/COD/ADM0/geoBoundaries-COD-ADM0.geojson

- level: 1
  boundary_year: 2017
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/COD/ADM1/geoBoundaries-COD-ADM1.geojson

- level: 2
  boundary_year: 2019
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/COD/ADM2/geoBoundaries-COD-ADM2.geojson

- level: 3
  boundary_year: 2010.0
  link: https://github.com/wmgeolab/geoBoundaries/raw/7278f6e1f5b609a1bab4f959015f040b809a5ac5/releaseData/gbOpen/COD/ADM3/geoBoundaries-COD-ADM3.geojson

