iso: GUM

links:
- level: 0
  boundary_year: 2021
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/GUM/ADM0/geoBoundaries-GUM-ADM0.geojson

- level: 2
  boundary_year: 2021
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/GUM/ADM2/geoBoundaries-GUM-ADM2.geojson

