iso: MKD

links:
- level: 0
  boundary_year: 2016
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/MKD/ADM0/geoBoundaries-MKD-ADM0.geojson

- level: 1
  boundary_year: 2016
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/MKD/ADM1/geoBoundaries-MKD-ADM1.geojson

- level: 2
  boundary_year: 2016
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/MKD/ADM2/geoBoundaries-MKD-ADM2.geojson

