adm: ADM5

links:
- iso: IND
  boundary_year: 2011
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/IND/ADM5/geoBoundaries-IND-ADM5.geojson

- iso: CAF
  boundary_year: 2020
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/CAF/ADM5/geoBoundaries-CAF-ADM5.geojson

- iso: RWA
  boundary_year: 2012
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/RWA/ADM5/geoBoundaries-RWA-ADM5.geojson

- iso: FRA
  boundary_year: 2020
  link: https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/FRA/ADM5/geoBoundaries-FRA-ADM5.geojson

